# Minimal local example

secret:
  existingDbSecret:
    enabled: true
    name: nexus-dbsecret
    usernameKey: db-user
    passwordKey: db-password
  nexusAdminSecret:
    enabled: true
    existingSecret:
      enabled: true
      name: nexus-adminsecret
      key: nexus-admin-password

postgresql:
  enabled: true
  database: nexus
  username: nexus
  password: "set-via-set-file"

pvc:
  storage: 20Gi

statefulset:
  container:
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "4Gi"

ingress:
  enabled: false

bootstrap:
  enabled: false
