{{- if not (and .Values.secret.existingDbSecret .Values.secret.existingDbSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.dbSecretName" . }}
  labels:
{{ include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  {{ include "nexus.dbSecretUsernameKey" . }}: {{ default (dig "auth" "username" "" .Values.postgresql) .Values.postgresql.username | required "A database username is required when secret.existingDbSecret.enabled=false" }}
  {{ include "nexus.dbSecretPasswordKey" . }}: {{ default (dig "auth" "password" "" .Values.postgresql) .Values.postgresql.password | required "A database password is required when secret.existingDbSecret.enabled=false" }}
{{- end }}