{{- if and .Values.secret.nexusSecret.enabled (not .Values.secret.nexusSecret.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.encryptionSecretName" . }}
  labels:
{{ include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ include "nexus.encryptionSecretKey" . }}: {{ .Values.secret.nexusSecret.secretKeyfile | b64enc }}
{{- end }}
