{{- if and .Values.secret.nexusAdminSecret.enabled (not (and .Values.secret.nexusAdminSecret.existingSecret .Values.secret.nexusAdminSecret.existingSecret.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.adminSecretName" . }}
  labels:
  {{- include "nexus.labels" . | nindent 4 }}
    {{- if .Values.nexus.extraLabels }}
      {{- with .Values.nexus.extraLabels }}
        {{ toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
type: Opaque
stringData:
  {{ include "nexus.adminSecretPasswordKey" . }}: {{ .Values.secret.nexusAdminSecret.adminPassword | required "A Nexus admin password is required when secret.nexusAdminSecret.existingSecret.enabled=false" }}
{{- end }}
